env:
  es6: true
  node: true

extends:
  - airbnb-base/legacy
  - plugin:jest/recommended
  - plugin:prettier/recommended

parser: babel-eslint
parserOptions:
  ecmaVersion: 8
  sourceType: module

rules:
  no-alert: error
  no-console: error
  no-constant-condition: error
  func-names: error
